import {BackfillRequest} from '../../request/models/backfillRequest';

export const REQUESTS: BackfillRequest[] = [
    // tslint:disable:max-line-length
    {RequestId: 100, ClientId: 200, ClientName: 'Quad/Graphics', HealthCenterId: 300, HeathCenterName: 'Sussex Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Illness', AdditionalInfo: '', EmployeeId: 1400, EmployeeName: 'John Smith' , RequesterEmployeeId: 121345, RequesterName: 'Sarah Ash', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 1, State: 'WI', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 110, ClientId: 200, ClientName: 'Quad/Graphics', HealthCenterId: 400, HeathCenterName: 'West Allis Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 2040, EmployeeName: 'Anne Gold', RequesterEmployeeId: 122345, RequesterName: 'Jim Poplar', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 3, State: 'IL', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New'  },
    {RequestId: 120, ClientId: 300, ClientName: 'Dow', HealthCenterId: 400, HeathCenterName: 'Dow Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 1004, EmployeeName: 'Julie Brown', RequesterEmployeeId: 123345, RequesterName: 'John Smith', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 5, State: 'WA', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 130, ClientId: 400, ClientName: 'Miller', HealthCenterId: 400, HeathCenterName: 'Miller Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 24030, EmployeeName: 'Kevin Oakes', RequesterEmployeeId: 142345, RequesterName: 'Jane Elm', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 7, State: 'VA', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 140, ClientId: 500, ClientName: 'Briggs', HealthCenterId: 400, HeathCenterName: 'Briggs Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 43040, EmployeeName: 'Jane Elm', RequesterEmployeeId: 123545, RequesterName: 'Casey Pine', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 6, State: 'IA', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 150, ClientId: 600, ClientName: 'Batesville', HealthCenterId: 400, HeathCenterName: 'Batesville Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 45007, EmployeeName: 'Sarah Ash', RequesterEmployeeId: 123645, RequesterName: 'Susan Hickory', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 9, State: 'NV', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 160, ClientId: 700, ClientName: 'Cova', HealthCenterId: 400, HeathCenterName: 'Virginia Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 44060, EmployeeName: 'Jim Poplar', RequesterEmployeeId: 123745, RequesterName: 'Kevin Oakes', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 8, State: 'FL', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 170, ClientId: 800, ClientName: 'City of Wichita Falls', HealthCenterId: 400, HeathCenterName: 'Wichita Falls Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 41000, EmployeeName: 'Casey Pine', RequesterEmployeeId: 123945, RequesterName: 'Julie Brown', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 2, State: 'GA', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },
    {RequestId: 180, ClientId: 900, ClientName: 'Safeway', HealthCenterId: 400, HeathCenterName: 'Safeway Clinic', StaffType: 'Temp', CoverageType: {Name: 'MA', Id: 333}, Department : 'Medical Clinic', Reason: 'Vacation', AdditionalInfo: '', EmployeeId: 40707, EmployeeName: 'Susan Hickory', RequesterEmployeeId: 123845, RequesterName: 'Anne Gold', OwnerId: 123, OwnerName: 'George Jones', Status: 'New', Priority: 4, State: 'AZ', TimeZone: '', HoursOfOperation: '', CoverageTypeName: 'New' },


];
